parameters:
#    biber_ltd_member_management.example.class: BiberLtd\Bundle\MemberManagementBundle\Example

services:
#    biber_ltd_member_management.example:
#        class: %biber_ltd_member_management.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
